export const CART_ADD_ITEM="CART_ADD_ITEM"
export const CART_REMOVE_ITEM='CART_REMOVE_ITEM'

export const CART_DB_ADD_ITEM_REQ="CART_ADD_ITEM"
export const CART_DB_ADD_ITEM_SUCCESS="CART_ADD_ITEM"
export const CART_DB_ADD_ITEM_FAIL="CART_ADD_ITEM"


export const CART_ITEMS_CLEAR=-"CART_ITEMS_CLEAR"


export const GET_CART_ITEMS_DB_REQ="GET_CART_ITEMS_DB_REQ"
export const GET_CART_ITEMS_DB_SUCCESS="GET_CART_ITEMS_DB_SUCCESS"



export const SAVE_SHIPPING_ADDRESS="SAVE_SHIPPING_ADDRESS"


export const CART_SAVE_PAYMENT_METHOD='CART_SAVE_PAYMENT_METHOD'




