export const ORDER_CREATE_REQ="ORDER_CREATE_REQ"
export const ORDER_CREATE_SUCCESS="ORDER_CREATE_SUCCESS"
export const ORDER_CREATE_FAIL="ORDER_CREATE_FAIL"


export const ORDER_DETAILS_REQ="ORDER_DETAILS_REQ"
export const ORDER_DETAILS_SUCCESS="ORDER_DETAILS_SUCCESS"
export const ORDER_DETAILS_FAIL="ORDER_DETAILS_FAIL"



export const ORDER_PAY_REQ="ORDER_PAY_REQ"
export const ORDER_PAY_SUCCESS="ORDER_PAY_SUCCESS"
export const ORDER_PAY_FAIL="ORDER_PAY_FAIL"
export const ORDER_PAY_RESET="ORDER_PAY_RESET"






export const ADMIN_ORDER_DEL_REQ="ADMIN_ORDER_DEL_REQ"
export const ADMIN_ORDER_DEL_SUCCESS="ADMIN_ORDER_DEL_SUCCESS"
export const ADMIN_ORDER_DEL_FAIL="ADMIN_ORDER_DEL_FAIL"
export const ADMIN_ORDER_DEL_RESET="ADMIN_ORDER_DEL_RESET"






export const MY_ORDER_LIST_REQ="MY_ORDER_LIST_REQ"
export const MY_ORDER_LIST_SUCCESS="MY_ORDER_LIST_SUCCESS"
export const MY_ORDER_LIST_FAIL="MY_ORDER_LIST_FAIL"




export const ADMIN_ORDER_LIST_REQ="ADMIN_ORDER_LIST_REQ"
export const ADMIN_ORDER_LIST_SUCCESS="ADMIN_ORDER_LIST_SUCCESS"
export const ADMIN_ORDER_LIST_FAIL="ADMIN_ORDER_LIST_FAIL"