export const PRODUCT_LIST_SUCCESS="PRODUCT_LIST_SUCCESS"
export const PRODUCT_LIST_FAIL="PRODUCT_LIST_FAIL"
export const PRODUCT_LIST_REQ="PRODUCT_LIST_REQ"





export const PRODUCT_SUCCESS="PRODUCT_SUCCESS"
export const PRODUCT_FAIL="PRODUCT_FAIL"
export const PRODUCT_REQ="PRODUCT_REQ"



export const PRODUCT_TOP_SUCCESS="PRODUCT_TOP_SUCCESS"
export const PRODUCT_TOP_FAIL="PRODUCT_TOP_FAIL"
export const PRODUCT_TOP_REQ="PRODUCT_TOP_REQ"



export const PRODUCT_CREATE_REVIEW_SUCCESS="PRODUCT_CREATE_REVIEW_SUCCESS"
export const PRODUCT_CREATE_REVIEW_REQ="PRODUCT_CREATE_REVIEW_REQ"
export const PRODUCT_CREATE_REVIEW_FAIL="PRODUCT_CREATE_REVIEW_FAIL"
export const PRODUCT_CREATE_REVIEW_RESET="PRODUCT_CREATE_REVIEW_RESET"




export const ADMIN_PRODUCT_DELETE_SUCCESS="ADMIN_PRODUCT_DELETE_SUCCESS"
export const ADMIN_PRODUCT_DELETE_FAIL="ADMIN_PRODUCT_DELETE_FAIL"
export const ADMIN_PRODUCT_DELETE_REQ="ADMIN_PRODUCT_DELETE_REQ"
export const ADMIN_PRODUCT_DELETE_RESET="ADMIN_PRODUCT_DELETE_RESET"




export const ADMIN_PRODUCT_CREATE_SUCCESS="ADMIN_PRODUCT_CREATE_SUCCESS"
export const ADMIN_PRODUCT_CREATE_FAIL="ADMIN_PRODUCT_CREATE_FAIL"
export const ADMIN_PRODUCT_CREATE_REQ="ADMIN_PRODUCT_CREATE_REQ"
export const ADMIN_PRODUCT_CREATE_RESET="ADMIN_PRODUCT_CREATE_RESET"



export const ADMIN_PRODUCT_UPDATE_SUCCESS="ADMIN_PRODUCT_UPDATE_SUCCESS"
export const ADMIN_PRODUCT_UPDATE_FAIL="ADMIN_PRODUCT_UPDATE_FAIL"
export const ADMIN_PRODUCT_UPDATE_REQ="ADMIN_PRODUCT_UPDATE_REQ"
export const ADMIN_PRODUCT_UPDATE_RESET="ADMIN_PRODUCT_UPDATE_RESET"