export const USER_LOGIN_REQ='USER_LOGIN_REQ'
export const USER_LOGIN_SUCCESS='USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL='USER_LOGIN_FAIL'
export const USER_LOGOUT='USER_LOGOUT'


export const USER_REGISTER_REQ='USER_REGISTER_REQ'
export const USER_REGISTER_SUCCESS='USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL='USER_REGISTER_FAIL'


export const USER_DETAILS_REQ='USER_DETAILS_REQ'
export const USER_DETAILS_SUCCESS='USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL='USER_DETAILS_FAIL'

export const USER_UPDATE_PROFILE_REQ='USER_UPDATE_PROFILE_REQ'
export const USER_UPDATE_PROFILE_SUCCESS='USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL='USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET='USER_UPDATE_PROFILE_RESET'    



export const ADMIN_USER_UPDATE_PROFILE_REQ='ADMIN_USER_UPDATE_PROFILE_REQ'
export const ADMIN_USER_UPDATE_PROFILE_SUCCESS='ADMIN_USER_UPDATE_PROFILE_SUCCESS'
export const ADMIN_USER_UPDATE_PROFILE_FAIL='ADMIN_USER_UPDATE_PROFILE_FAIL'
export const ADMIN_USER_UPDATE_PROFILE_RESET='ADMIN_USER_UPDATE_PROFILE_RESET'  



export const USER_LIST_REQ='USER_LIST_REQ'
export const USER_LIST_SUCCESS='USER_LIST_SUCCESS'
export const USER_LIST_FAIL='USER_LIST_FAIL'
export const USER_LIST_RESET='USER_LIST_RESET'


export const USER_DELETE_REQ='USER_DELETE_REQ'
export const USER_DELETE_SUCCESS='USER_DELETE_SUCCESS'
export const USER_DELETE_FAIL='USER_DELETE_FAIL'



